### ISSUE TITLE
Should CPUFriend be configured after installation?

### ISSUE THREAD

**Issue by trevorwdunn** [hackintosh-club/intel-nuc10#100]
Looked into it some and the CPUFriend Documentation says that if you're not sure then it probably isn't required. I'm having fans running a lot though, and the NUC seems to be generating more heat than it should. 

Processor is i5-10210U

**Comment by apollohackintosh** [comment]
This was resolved in the latest EFI, fans are nice and silent.

**Comment by trevorwdunn** [comment]
I'll take a look and see if I can replicate the new results. I think it's time for me to replace a NUC8 system anyway. It would be good to use a 10 if I can, as the 8 has that fan issue.
