### ISSUE TITLE
System does not shutdown, reboots every time

### ISSUE THREAD

**Issue by apollohackintosh** [hackintosh-club/intel-nuc10#101]
I am having this issue after the latest opencore upgrade. I have no yet tried the patch for fixing shutdown:
https://github.com/Koala166/The-TLDR-Guide-of-Fixing-Shutdown-Restart
Would you be able to tell me the USB controller location so that I can try this out and see if it fixes the issue?

**Comment by WuLongMiTaoLaiYiDa** [comment]
Try the latest EFI   ; - )
