### ISSUE TITLE
NUC10i7FNH got brick!!!

### ISSUE THREAD

**Issue by duyquang91** [hackintosh-club/intel-nuc10#102]
I updated BIOS to latest version [FNCML357.0060](https://www.intel.com/content/www/us/en/download/19485/bios-update-fncml357.html) then updated open core [v0.9.2.0508 OpenCore 0.9.2 ](https://github.com/hackintosh-efi/intel-nuc10/releases/tag/v0.9.2.0508). I installed latest Ventura 13.4, downloaded latest stable version of [AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0/AirportItlwm_v2.2.0_stable_BigSur.kext.zip) (v2.2.0-stable). Everything work well, wifi & bluetooth also work.

Today, I lock the screen & my NUC goes to sleep, when I wake it up by the power button, the NUC got brick! The LED & fan just work a few seconds then completely shutdown, I cannot boot to BIOS anymore! I contacted to Intel for the warranty then got a tutorial to teardown the NUC, unplug the CMOS battery for 15 minutes & then it can turn on again! I have to unlock the CFG again & everything back to normal. It took the whole weekend to figure it out!

**Conclusions:**
1. Do not update to latest BIOS [FNCML357.0060](https://www.intel.com/content/www/us/en/download/19485/bios-update-fncml357.html) for now (not sure if it is the root cause). I read on the internet so many people get issues with NUC10i7FNH BIOS update even with Windows! I downgraded back to 0055 version. Hope it is stable.
2. Shouldn't let NUC go to sleep. I'm not sure if anyone face any issues with sleep?
3. I am not sure [AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0/AirportItlwm_v2.2.0_stable_BigSur.kext.zip) (v2.2.0-stable) cause any issues because sometime bluetooth doesn't work & cause the kernel panic on Ventura, I feel like it is unstable then I downgraded MacOS to Monterey which is quite more stable & safe!

**Comment by Daasin** [comment]
You can downgrade your BIOS on a NUC, even if bricked? Recently ordered a 10th Gen NUC and going to try to unlock the CFGLock using this repo but unsure if it stays that way after a firmware upgrade. 🤔

**Comment by WuLongMiTaoLaiYiDa** [comment]
Thank you for your feedback. Please try using the latest Intel wireless kext
