### ISSUE TITLE
usb-c to HDMI iusses (semi-solved), overheating (solved), airdrop not working (Nuc10i5)

### ISSUE THREAD

**Issue by Nuchintosher90** [hackintosh-club/intel-nuc10#103]
Hi everyone,

I successfully installed the latest version of MacOS Ventura, I encountered these little glitches:

I tried to connect via USB-C to HDMI cable but after the apple loading screen it comes up with a black screen.

Using the NUC with the Hackintosh system, I notice that the temperatures are many wings compared to those of windows, have any of you encountered the same problem?

Maybe I read wrong, but in theory airdrop should also work with the new wifi driver update, is that correct? I can see my iphone, but i can't send anything.

Sorry for all these requests, I hope some of you can help me out.

**Comment by alexookah** [comment]
I had a similar problem and solved it by changing in bios:
Video
IGD Primary Video Port -> HDMI
IGD Secondary Video Port  (thunderbolt) -> None

**Comment by JSymbiosis** [comment]
The following fixed my video issues however I'm still playing with the memory values as I'm running a 4K display with HDR.

https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html#deviceproperties

https://elitemacx86.com/threads/how-to-enable-intel-hd-and-uhd-graphics-on-macos-intel-framebuffer-patching-guide.931/

Add the following to the config.plist file as shown in the screenshot or dortania guide above.

framebuffer-patch-enable | Data | 01000000
framebuffer-stolenmem | Data | 00003001
framebuffer-fbmem | Data | 00009000

<img width="1171" alt="Screen Shot 2023-09-09 at 12 01 07 PM" src="https://github.com/hackintosh-club/intel-nuc10/assets/144549614/cb6d599f-7bb7-4fee-8479-82584c86b444">

**Comment by WuLongMiTaoLaiYiDa** [comment]
> I had a similar problem and solved it by changing in bios: Video IGD Primary Video Port -> HDMI (instead of AUTO) IGD Secondary Video Port (thunderbolt) -> None

Thank you for your suggestion. It has been adopted
