### ISSUE TITLE
CFGLock issue - problem writing variable

### ISSUE THREAD

**Issue by alexookah** [hackintosh-club/intel-nuc10#104]
I am trying to unlock using the `CFGLock` but have some issues.
I am getting an error `problem writing variable.`

I might have updated the bios to 0.59 and downgraded back to 0.55. 
Could it be that 0.59 permanently block using the CFGLock?
or is there some other resolution to the problem writing variable?

@mrasong

**Comment by mrasong** [comment]
By now, only down to 055 can unlock `CFGLock`

1. Down to 055
2. unlock CFGLock
3. Upgrade to 059

**Comment by alexookah** [comment]
I had to first upgrade to 0.59 and then downgrade to 0.55 in order to unlock CFG

**Comment by aryanrajseo** [comment]
getting same error, i am on 0061 and i need 0055 bios but it is no longer available. https://www.asus.com/supportonly/nuc10i5fnh/helpdesk_bios/

anyone have the old bios file?

**Comment by aryanrajseo** [comment]
found 0052 https://drivers.softpedia.com/dyn-search.php?search_term=NUC10I5FNH&p_sortby=0&p_category=10&p_picks=&p_license=&p_lastupdate=0&p_whatos=0
