### ISSUE TITLE
[0.9.3] bluetooth not working

### ISSUE THREAD

**Issue by alexookah** [hackintosh-club/intel-nuc10#106]
Hello
I am using the latest 0.9.3 EFI version
I just changed in the config.plist
`MLB, Serial & SmUUID`

I am using BIOS `0059` with CFG unlocked.
Tried Reset NVRAM.
I updated from Monterey to mac OS Ventura

The **Bluetooth** doesn't seem to be working.
In mac info -> Bluetooth address may appear as `NULL`

I am trying to enable but doesn't seem to be able to enable.
Is there something that should be done ?

P.S.:
Checking out some info about Bluetooth firmware I noticed that:
`IntelBluetoothInjector` should be removed from kexts folder because of [this](https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-does-this-kext-do)

**Comment by aschwabe** [comment]
Im having the same problem.  I tried swapping out recent versions of the bluetooth kexts as well with no change.

**Comment by lluisrb** [comment]
Hi, same issue here. I’ve tried also reinstalling from scratch but no luck. Something broke the Bluetooth in 0.9.3 or in the latest kexts

**Comment by zarkun** [comment]
I too had the same problem.
This problem also occurred when performing NVRAM Reset.

However, I solved it in the following way.
1. Delete the Kext for Bluetooth from config.plist.
2. Boot up. (MAC Info: Bluetooth device does not appear.)
3. Add the kext for bluetooth that you deleted in config.plist.
4. Reboot with the modified config.plist.
5. The bluetooth device is newly recognized in MAC Info.
6. I was able to connect bluetooth keyboard and mouse device etc.

**Comment by lluisrb** [comment]
Hi
@zarkun thxs for your suggestion but unfortunately your solution didn't work for me.
But I've found another that worked for me, I hope it is useful for most of you.

Bluetooth was broken with the MacOS 13.4 update. Add the below child items to NVRAM>7C436110-AB2A-4BBB-A880-FE41995C9F82 section in your config.plist file to fix it:

Key | Type | Value
bluetoothInternalControllerInfo | Data | 00000000 00000000 00000000 0000
bluetoothExternalDongleFailed | Data | 00

(credits for Seven_of_eleven)

**Comment by Randy615** [comment]
Hello can you help me do it in more detail please I do not understand much this I'm in version 3.5 but I do not know how to do what they say in the EFI

**Comment by mrasong** [comment]
you can try to update `AirportItlwm.kext` to the latest version.

**Comment by aschwabe** [comment]
Tried all of the above, and bluetooth is still not working.  Upgrade to 13.5, added keys to config.plist, updated airport kext.  The same null device id shows up and doesn't work.

**Comment by aschwabe** [comment]
> Hello can you help me do it in more detail please I do not understand much this I'm in version 3.5 but I do not know how to do what they say in the EFI

Look at the program ProperTree for editing config.plist, and adding/editing is very easy.  You will understand the notes above better.

**Comment by aschwabe** [comment]
I wonder if it is dependent or specific to intel NUC firmware versions ?

**Comment by lluisrb** [comment]
I added the NVRAM keys using Open Core auxiliary Tools. I have also updated firmware to the latest 061 version without problems (previously unlocked on 055) and Bluetooth still working.

**Comment by lluisrb** [comment]
One more thing :)))) forgot to mention that I also updated Open core to 0.9.4 and everything is still working fine

**Comment by aschwabe** [comment]
Upgrade to 0.9.4 release fixes bluetooth for Ventura 13.5.  No changes from release files except platform info.

**Comment by mrasong** [comment]
> Upgrade to 0.9.4 release fixes bluetooth for Ventura 13.5. No changes from release files except platform info.


[https://hackintosh.club/d/10000055](https://hackintosh.club/d/10000055)

this may fix BT issue.
