### ISSUE TITLE
Upgrade MacOs Sonoma 14.0

### ISSUE THREAD

**Issue by jktan0504** [hackintosh-club/intel-nuc10#110]
Hi, experts, you did a great job so far. Please help us upgrade to macos sonoma 14.0 too.

Thanks experts

请大大务必继续帮忙升级到 macos sonoma 14.0

感恩大大

![Screenshot 2023-10-09 at 4 51 19 PM](https://github.com/hackintosh-club/intel-nuc10/assets/29939040/6e8077d8-e329-4a9e-baed-5f512b962e24)
![Screenshot 2023-10-09 at 4 51 30 PM](https://github.com/hackintosh-club/intel-nuc10/assets/29939040/de888704-15d3-4498-b84d-02d8b25215c5)

**Comment by WuLongMiTaoLaiYiDa** [comment]
在app strore里搜索Sonoma
下载全量包进行更新

**Comment by WuLongMiTaoLaiYiDa** [comment]
或者使用终端输入命令   sudo softwareupdate -ai --restart
重启resetnvram之后进行更新

**Comment by jktan0504** [comment]
谢谢大神
@WuLongMiTaoLaiYiDa 

的确可以升级了

不过目前我的Wifi 打不开

请问怎么解决呢？

**Comment by jktan0504** [comment]
![Uploading Screenshot 2023-10-17 at 12.56.26 PM.png…]()
