### ISSUE TITLE
Unable to toggle and switch on Wifi on MacOs Sonoma 14.0

### ISSUE THREAD

**Issue by jktan0504** [hackintosh-club/intel-nuc10#111]
Hi experts, I cannot turn on or switch on the wifi toggle on macos Sonoma.
Any help from this ?
Thanks 

![Screenshot 2023-10-17 at 12 56 26 PM](https://github.com/hackintosh-club/intel-nuc10/assets/29939040/ccd67d13-ab94-48ab-9dfc-8e934b66e0a2)

![Screenshot 2023-10-17 at 12 56 41 PM](https://github.com/hackintosh-club/intel-nuc10/assets/29939040/2d42b02a-7113-40b3-81f1-383253faa3a4)

Thanks

大神 我升级之后 不能打开 WiFi
请大神帮帮忙

非常感谢

**Comment by jktan0504** [comment]
`
`

**Comment by jktan0504** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>21G651</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>AirportItlwm</string>
	<key>CFBundleIdentifier</key>
	<string>com.zxystd.AirportItlwm</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>AirportItlwm</string>
	<key>CFBundlePackageType</key>
	<string>KEXT</string>
	<key>CFBundleShortVersionString</key>
	<string>2.3.0</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>2.3.0</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>14C18</string>
	<key>DTPlatformName</key>
	<string>macosx</string>
	<key>DTPlatformVersion</key>
	<string>13.1</string>
	<key>DTSDKBuild</key>
	<string>22C55</string>
	<key>DTSDKName</key>
	<string>macosx13.1</string>
	<key>DTXcode</key>
	<string>1420</string>
	<key>DTXcodeBuild</key>
	<string>14C18</string>
	<key>IOKitPersonalities</key>
	<dict>
		<key>itlwm</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.zxystd.AirportItlwm</string>
			<key>IOClass</key>
			<string>AirportItlwm</string>
			<key>IOMatchCategory</key>
			<string>IODefaultMatchCategory</string>
			<key>IOPCIMatch</key>
			<string>0x27238086 0x43F08086 0xA0F08086 0x34F08086 0x4DF08086 0x02F08086 0x3DF08086 0x06F08086 0x27208086 0x08b18086 0x08b28086 0x08b38086 0x08b48086 0x095a8086 0x095b8086 0x31658086 0x31668086 0x24f38086 0x24f48086 0x24f58086 0x24f68086 0x24fb8086 0x24fd8086 0x25268086 0x9df08086 0xa3708086 0x31DC8086 0x30DC8086 0x271C8086 0x271B8086 0x42a48086 0x00a08086 0x00a48086 0x02a08086 0x40a48086 0x00608086 0x00648086 0x02608086 0x02648086 0x42298086 0x422b8086 0x422c8086 0x42308086 0x42328086 0x42358086 0x42368086 0x42378086 0x42388086 0x42398086 0x423a8086 0x423b8086 0x423c8086 0x423d8086 0x00828086 0x00838086 0x00848086 0x00858086 0x00878086 0x00898086 0x008a8086 0x008b8086 0x00908086 0x00918086 0x08928086 0x08938086 0x08948086 0x08958086 0x08968086 0x08978086 0x08ae8086 0x08af8086 0x088e8086 0x088f8086 0x08908086 0x08918086 0x08878086 0x08888086 0x27258086 0x27268086 0x7A708086 0x7AF08086 0x51F08086 0x54F08086 0x27298086 0x7E408086</string>
			<key>IOProbeScore</key>
			<integer>2000</integer>
			<key>IOProviderClass</key>
			<string>IOPCIDevice</string>
		</dict>
	</dict>
	<key>LSMinimumSystemVersion</key>
	<string>10.15</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2020 钟先耀. All rights reserved.</string>
	<key>OSBundleLibraries</key>
	<dict>
		<key>com.apple.iokit.IO80211FamilyLegacy</key>
		<string>600.0</string>
		<key>com.apple.iokit.IONetworkingFamily</key>
		<string>3.2</string>
		<key>com.apple.iokit.IOPCIFamily</key>
		<string>2.9</string>
		<key>com.apple.kpi.bsd</key>
		<string>16.7</string>
		<key>com.apple.kpi.iokit</key>
		<string>16.7</string>
		<key>com.apple.kpi.libkern</key>
		<string>16.7</string>
		<key>com.apple.kpi.mach</key>
		<string>16.7</string>
	</dict>
	<key>OSBundleRequired</key>
	<string>Network-Root</string>
</dict>
</plist>
`

**Comment by jktan0504** [comment]
`<code></code>
`

**Comment by jktan0504** [comment]
[Sonoma_RS.zip](https://github.com/hackintosh-club/intel-nuc10/files/12925148/Sonoma_RS.zip)

**Comment by mrasong** [comment]
升级14系统后，需要手动替换Wifi驱动， [AirportItlwm.kext](https://github.com/OpenIntelWireless/itlwm)

**Comment by jktan0504** [comment]
完成没问题了
谢谢大神 @mrasong

**Comment by eliasli77** [comment]
@jktan0504  你好 请问你是怎么解决的  我尝试更换了驱动文件  但是问题没有得到解决

**Comment by apollohackintosh** [comment]
> Hi experts, I cannot turn on or switch on the wifi toggle on macos Sonoma.
> Any help from this ?
> Thanks 
> 
> ![Screenshot 2023-10-17 at 12 56 26 PM](https://github.com/hackintosh-club/intel-nuc10/assets/29939040/ccd67d13-ab94-48ab-9dfc-8e934b66e0a2)
> 
> ![Screenshot 2023-10-17 at 12 56 41 PM](https://github.com/hackintosh-club/intel-nuc10/assets/29939040/2d42b02a-7113-40b3-81f1-383253faa3a4)
> 
> Thanks
> 
> 大神 我升级之后 不能打开 WiFi
> 请大神帮帮忙
> 
> 非常感谢

How did you manage to install Sonoma? I keep getting an error when trying.

**Comment by jktan0504** [comment]
@apollohackintosh just download & install it from apps store.

**Comment by apollohackintosh** [comment]
> @apollohackintosh just download & install it from apps store.

Keeps giving me an error
