### ISSUE TITLE
Loading system blocked...

### ISSUE THREAD

**Issue by speedball82** [hackintosh-club/intel-nuc10#112]
Hi I've try to install in nuc 10 i7, but during the configuration before the installation appears the bar will freeze, without continuing I've also tried to reset nvram but nothing, the CFG LOCK is ok, can be it bricked? Where I fault?

**Comment by jktan0504** [comment]
HI, do you mind to teach me how do we reset nvram on intel nuc 10 ?
@speedball82

**Comment by speedball82** [comment]
I have reset the nvram only by the option in open core booting option, I don't know any other mode to reset it.

**Comment by jktan0504** [comment]
open core booting option ?
do you mind take some photo

**Comment by mrasong** [comment]
Press SPACE when you are in OC booting creen, then you can find the Reset NVRAM option.

**Comment by mrasong** [comment]
> Hi I've try to install in nuc 10 i7, but during the configuration before the installation appears the bar will freeze, without continuing I've also tried to reset nvram but nothing, the CFG LOCK is ok, can be it bricked? Where I fault?

What SSD did you use?

**Comment by mrasong** [comment]
Some samsung SSD/NVMe do not support to install hackintosh.

**Comment by speedball82** [comment]
Sorry for delay, I'm using an ssd SKhynix, today I've checked and seems this drive isn't compatible, in the weekend I try with a samsung 970 evo, I've at my home and I will update you. Thanks for your support.

**Comment by mrasong** [comment]
The `970 EVO` doesn't work either!
Try to use a WD NVMe instead.

**Comment by fre4ki** [comment]
I've installed it with a WD 850X NVME.

**Comment by WuLongMiTaoLaiYiDa** [comment]
> Sorry for delay, I'm using an ssd SKhynix, today I've checked and seems this drive isn't compatible, in the weekend I try with a samsung 970 evo, I've at my home and I will update you. Thanks for your support.

SKhynix don't support hackintosh
