### ISSUE TITLE
MacOS Sonoma, Not showing updates

### ISSUE THREAD

**Issue by nighthsade875** [hackintosh-club/intel-nuc10#115]
when i look at the software updates on macos sonoma, it says im on the latest version 14.1.2 but i know that 14.2 is out and the 14.3 beta is also out, wondering if anyone has been able to find a fix

**Comment by apollohackintosh** [comment]
You have to redownload the whole image from the app store and install it that way. A bit of a pain but it does the job.

**Comment by jktan0504** [comment]
haha i see. thanks. I tot apple did not update. Now my version is still 14.0 =D

**Comment by kababoom** [comment]
Have a look at this closed one: #122 got some useful info about updating
