### ISSUE TITLE
DRM issue

### ISSUE THREAD

**Issue by speedball82** [hackintosh-club/intel-nuc10#117]
Hi everyone, I've tried to open video with Prime Video but there is an error, it seems DRM problem. Does anyone heppend?

**Comment by apollohackintosh** [comment]
> Hi everyone, I've tried to open video with Prime Video but there is an error, it seems DRM problem. Does anyone heppend?

Post MacOS Montery this will always happen so if you open them on chrome it will run. This is unfixable on any hackintoshs.

**Comment by speedball82** [comment]
Thks.

**Comment by WuLongMiTaoLaiYiDa** [comment]
UHD Graphics can't use DRM on hackintosh , Only use AMD GPU can make DRM work
