### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by hele204** [hackintosh-club/intel-nuc10#119]
大佬,我已经解锁了CFGLock,然后锁屏按esc后一段时间(比如第二天),按键盘后显示器有反应但是一直黑屏,然后等一段时间nuc重启,出现如下错误:
panic(cpu 2 caller 0xffffff802229089b): userspace watchdog timeout: no successful checkins from WindowServer (2 induced crashes) in 120 seconds
WindowServer has not exited since first loaded
service: logd, total successful checkins in 42984 seconds: 4299, last successful checkin: 0 seconds ago
service: WindowServer (2 induced crashes), total successful checkins in 42951 seconds: 4283, last successful checkin: 120 seconds ago
service: opendirectoryd, total successful checkins in 42984 seconds: 4298, last successful checkin: 0 seconds ago
service: configd, total successful checkins in 42984 seconds: 4299, last successful checkin: 0 seconds ago

Panicked task 0xffffff954603a008: 3 threads: pid 108: watchdogd
Backtrace (CPU 2), panicked thread: 0xffffff9543cb0598, Frame : Return Address
0xffffffc8a553f510 : 0xffffff801f636c41 mach_kernel : _handle_debugger_trap + 0x4b1
0xffffffc8a553f560 : 0xffffff801f795310 mach_kernel : _kdp_i386_trap + 0x110
0xffffffc8a553f5a0 : 0xffffff801f784a5c mach_kernel : _kernel_trap + 0x55c
0xffffffc8a553f620 : 0xffffff801f5d3971 mach_kernel : _return_from_trap + 0xc1
0xffffffc8a553f640 : 0xffffff801f636f2d mach_kernel : _DebuggerTrapWithState + 0x5d
0xffffffc8a553f730 : 0xffffff801f6365d3 mach_kernel : _panic_trap_to_debugger + 0x1e3
0xffffffc8a553f790 : 0xffffff801fdd8d2e mach_kernel : _panic_with_options + 0x89
0xffffffc8a553f880 : 0xffffff802229089b com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xffffffc8a553f890 : 0xffffff8022290364 com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments + 0x2e
0xffffffc8a553f8b0 : 0xffffff802228f42b com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x83
0xffffffc8a553f9e0 : 0xffffff801fd4e326 mach_kernel : __ZN12IOUserClient18callExternalMethodEjP25IOExternalMethodArguments + 0x86
0xffffffc8a553fa10 : 0xffffff801fd4e69d mach_kernel : _is_io_connect_method + 0x31d
0xffffffc8a553fb80 : 0xffffff801f7404cf mach_kernel : _iokit_server_routine + 0x3aef
0xffffffc8a553fca0 : 0xffffff801f60f8a0 mach_kernel : _ipc_kmsg_send + 0x570
0xffffffc8a553fd60 : 0xffffff801f6276b8 mach_kernel : _mach_msg_overwrite_trap + 0x5d8
0xffffffc8a553fdd0 : 0xffffff801f627d28 mach_kernel : _mach_msg2_trap + 0x3b8
0xffffffc8a553fef0 : 0xffffff801f76a052 mach_kernel : _mach_call_munger64 + 0x1f2
0xffffffc8a553ffa0 : 0xffffff801f5d3dd6 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[F1797B78-7645-3FC6-AD29-624DD0826DA0]@0xffffff802228e000->0xffffff8022290fff

Process name corresponding to current thread (0xffffff9543cb0598): watchdogd
Boot args: keepsyms=1 debug=0x100 igfxonln=1

Mac OS version:
23C71

Kernel version:
Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
Kernel UUID: F73CFE5A-7EF6-3C21-AFA7-742645B733CC
roots installed: 0

**Comment by wsqun** [comment]
我遇到一个问题是 nuc无法通过usb唤醒，只能再摁下电源键

**Comment by mrasong** [comment]
试试最新的EFI
