### ISSUE TITLE
Restart looping on installing Sonoma 14.4

### ISSUE THREAD

**Issue by SamuelNWK** [hackintosh-club/intel-nuc10#122]
I used [https://github.com/hackintosh-club/intel-nuc10/releases/tag/v0.9.9.0311](v0.9.9) to upgrade Ventura to Sonoma 14.4. But restarted looping on installation.
Can anyone help?

**Comment by mrasong** [comment]
Stay in 14.3.1 maybe a wise choice

**Comment by mrasong** [comment]
There are too many issues in 14.4

**Comment by WuLongMiTaoLaiYiDa** [comment]
download itlwm kext [v2.3.0-alpha](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha) here
this kext Only for Intel WiFi Sonoma 14.4 user
[AirportItlwm-Sonoma14.4](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma14.4-v2.3.0-DEBUG-alpha-ae9572e.zip)

change config.pist -- misc -- security -- securebootmodel -- Disabled

use resetnvram.efi  in OC UI with space button

reupdate in macos

**Comment by SamuelNWK** [comment]
> Stay in 14.3.1 maybe a wise choice

You are right. I can upgrade to Sonoma 14.3.1 by using this version successfully. Thanks.

**Comment by SamuelNWK** [comment]
> download itlwm kext [v2.3.0-alpha](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha) here this kext Only for Intel WiFi Sonoma 14.4 user [AirportItlwm-Sonoma14.4](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma14.4-v2.3.0-DEBUG-alpha-ae9572e.zip)
> 
> change config.pist -- misc -- security -- securebootmodel -- Disabled
> 
> use resetnvram.efi in OC UI with space button
> 
> reupdate in macos

I'll give it a try. Thanks!
