### ISSUE TITLE
Cannot update to 14.4.1

### ISSUE THREAD

**Issue by apollohackintosh** [hackintosh-club/intel-nuc10#124]
I tried downloading the latest sonoma from settings and from the app store, neither is installing. When downloaded from the app store it goes through the installation process, takes it's time but yet upon boot it is still on 14.2. Is there any other way to install the latest update?

**Comment by WuLongMiTaoLaiYiDa** [comment]
please use lastest EFI OC0.9.9 2424330
Do reset nvram once
get into macos
ota again

**Comment by apollohackintosh** [comment]
> please use lastest EFI OC0.9.9 2024330 Do reset nvram once get into macos ota again

Thanks but it didn't work. I reset the nvramnd i'm on the latest EFI as well. Downloaded 14.4.1 from the app store and it still did not install. It went through the whole process, installing and upon reboot it just comes back to 14.2

**Comment by apollohackintosh** [comment]
> please use lastest EFI OC0.9.9 2024330 Do reset nvram once get into macos ota again

I am on the old BIOS, could that be the reason? I think i'm on 53.

**Comment by apollohackintosh** [comment]
https://www.youtube.com/watch?v=Z9va5xRtuvw resolved the issue.
