### ISSUE TITLE
mac os 13 boot looping

### ISSUE THREAD

**Issue by lakshan-btwarch** [hackintosh-club/intel-nuc10#125]
i instaled mac os 13 in muc intel nuc10i7fnh and it is bootlooping 

nvme samsung 970 evo

ssd crucal mx 500

**Comment by apollohackintosh** [comment]
> i instaled mac os 13 in muc intel nuc10i7fnh and it is bootlooping
> 
> nvme samsung 970 evo
> 
> ssd crucal mx 500

This can be an issue with any one of the drivers. Can you run through the steps of what you did to create the installation USB?

**Comment by msf999** [comment]
Same problem here, I followed Dortania guide by downloading Sonoma using the App Store:
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html

I get `no bootable device was found` when the NUC reboots. Is it the same for you?

**Comment by apollohackintosh** [comment]
> Same problem here, I followed Dortania guide by downloading Sonoma using the App Store: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html
> 
> I get `no bootable device was found` when the NUC reboots. Is it the same for you?

That means you've set up your USB incorrectly. Leave the EFI on a Fat32 formatted USB still and then follow the process of downloading the recovery image if not already and then create the correct folder structure. Or have you already installed it and it cannot boot?

**Comment by msf999** [comment]
> > Same problem here, I followed Dortania guide by downloading Sonoma using the App Store: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html
> 
> > 
> 
> > I get `no bootable device was found` when the NUC reboots. Is it the same for you?
> 
> 
> 
> That means you've set up your USB incorrectly. Leave the EFI on a Fat32 formatted USB still and then follow the process of downloading the recovery image if not already and then create the correct folder structure. Or have you already installed it and it cannot boot?

Thanks! Got it to work using a different USB drive.
