### ISSUE TITLE
Boot looping in i3 10th gen nuc

### ISSUE THREAD

**Issue by aryanrajseo** [hackintosh-club/intel-nuc10#131]
Having Similar issue when i  setup with windows+moneterey in same drive. ( Loop Issue)

```
Model - BXNUC10i3FNHN (i3-10110U)
SSD - Samsung 970 EVO
USB Drive - HP x796w USB 3.2 Flash Drive in mac os extended.
OS - Monetery installer is created and EFI is placed.
```

Errors -
1. CFGLock Unlock option is not found. Setting value 0 shows error on bios 0058 so failed to do that.
2. The Instllation seems get succeed but keep looping.

Formated the Disk again with core Monetry Install and it shows the following error 3.

`A bootable device has not been detected.`

**I don't see the NVME Samsung 970 EVO drive with F10.**

Do i need to use FAT32 EFI usb drive?
![WhatsApp Image 2024-07-01 at 10 26 13 AM](https://github.com/hackintosh-club/intel-nuc10/assets/34836534/e991af7b-0861-4825-aba0-f98be77c9bca)
![WhatsApp Image 2024-07-01 at 10 26 12 AM](https://github.com/hackintosh-club/intel-nuc10/assets/34836534/962481f9-dd3c-4bb6-9bb2-3f6d138b8016)
![WhatsApp Image 2024-07-01 at 10 26 11 AM (1)](https://github.com/hackintosh-club/intel-nuc10/assets/34836534/fd39a2e1-e743-4d60-887c-dc0f5536081d)

**Comment by aryanrajseo** [comment]
i checked the efi and some of the .kext like USBMaptool was missing, i added them and checked the AppleXcpmCfgLock.
It seems to boot and work. i will now review the changes. What i am missing with CGLock? and how to fix the variable writing?

https://browser.geekbench.com/v6/cpu/6742160

**Comment by aryanrajseo** [comment]
Strange the default EFI seems to work normally without any change. However with installation, the nvme got EFI/Apple/ folder.

**Comment by WuLongMiTaoLaiYiDa** [comment]
> Having Similar issue when i setup with windows+moneterey in same drive. ( Loop Issue)
> 
> ```
> Model - BXNUC10i3FNHN (i3-10110U)
> SSD - Samsung 970 EVO
> USB Drive - HP x796w USB 3.2 Flash Drive in mac os extended.
> OS - Monetery installer is created and EFI is placed.
> ```
> 
> Errors -
> 
> 1. CFGLock Unlock option is not found. Setting value 0 shows error on bios 0058 so failed to do that.
> 2. The Instllation seems get succeed but keep looping.
> 
> Formated the Disk again with core Monetry Install and it shows the following error 3.
> 
> `A bootable device has not been detected.`
> 
> **I don't see the NVME Samsung 970 EVO drive with F10.**
> 
> Do i need to use FAT32 EFI usb drive? ![WhatsApp Image 2024-07-01 at 10 26 13 AM](https://private-user-images.githubusercontent.com/34836534/344551837-e991af7b-0861-4825-aba0-f98be77c9bca.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjUyOTIsIm5iZiI6MTcyMjIyNDk5MiwicGF0aCI6Ii8zNDgzNjUzNC8zNDQ1NTE4MzctZTk5MWFmN2ItMDg2MS00ODI1LWFiYTAtZjk4YmU3N2M5YmNhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMzQ5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGMwOGZjOGJmZWRjNWU2NGFhOWNhNDUwM2E0MjQ1OGFiNjYyZmM4MjFhM2NlYWRmZWJlNTcyZTY2OWYzNTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fT_IDuEZrMLyrac3NYE_zafAQoGV2IXS2Q_JXd6W7c4) ![WhatsApp Image 2024-07-01 at 10 26 12 AM](https://private-user-images.githubusercontent.com/34836534/344551833-962481f9-dd3c-4bb6-9bb2-3f6d138b8016.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjUyOTIsIm5iZiI6MTcyMjIyNDk5MiwicGF0aCI6Ii8zNDgzNjUzNC8zNDQ1NTE4MzMtOTYyNDgxZjktZGQzYy00YmI2LTliYjItM2Y2ZDEzOGI4MDE2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMzQ5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzlhZjI5M2JmMzQ5YjQ1NzRmYzgwYjY1NjNhYjdiMDM2ZjEzY2MyYzdkOWQ5MDQ3ZWY5MjcxN2YwNDRmMDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SoggxF9mW-BVu_xdPsC0zK5R2KoWqKxAGDD1xkIzqss) ![WhatsApp Image 2024-07-01 at 10 26 11 AM (1)](https://private-user-images.githubusercontent.com/34836534/344551830-fd39a2e1-e743-4d60-887c-dc0f5536081d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjUyOTIsIm5iZiI6MTcyMjIyNDk5MiwicGF0aCI6Ii8zNDgzNjUzNC8zNDQ1NTE4MzAtZmQzOWEyZTEtZTc0My00ZDYwLTg4N2MtZGMwZjU1MzYwODFkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMzQ5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjlmYzE1ZmZkOTFmYmYwNTBiYTk0MjU5NjA4YzFhYmNkMmQxYmMyZGI3MWRmZjMzOTBjZjE4MDlmZGZkYzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iQmeqx9INbV3ogfK2RA3FRP2-L_JAnF8isiIyPUvKps)

Enter choice ：    2

Do you want to toggle the value y/n    :  y

Variable read: value 1  

after  unlock cfg lock  this option read  0   that's correct
