### ISSUE TITLE
sequoia?

### ISSUE THREAD

**Issue by msf999** [hackintosh-club/intel-nuc10#135]
Anyone tried upgrading to sequoia? Is everything running fine?

**Comment by jktan0504** [comment]
I am also waiting for the good news.

![Screenshot 2024-09-25 at 9 48 58 AM](https://github.com/user-attachments/assets/c7427930-48d6-4267-92aa-8e6afc0e9f0d)

**Comment by nikitajeganpp** [comment]
I have updated to Sequoia. The system is running fine except Bluetooth and Wifi don't work anymore. The toggle in the top bar cannot be turned on anymore. This seems like a driver problem to me. macOS does not recognize BT and Wifi.

The rest seems to work just fine.

Hope a new release will come soon.

**Comment by nikitajeganpp** [comment]
I have updated to sequoia. Seems to work fine except BT and wifi are not working.

**Comment by WuLongMiTaoLaiYiDa** [comment]
update oc 1.0.2 , now u can update macOS Sequoia with the EFI， WiFi need oclp patch

**Comment by guliujian** [comment]
> update oc 1.0.2 , now u can update macOS Sequoia with the EFI， WiFi need oclp patch

i used the latest config.plist and file , when i boot into system which is sequoia ,the oclp patch is gray in app, how can it be applied?

**Comment by apollohackintosh** [comment]
> > update oc 1.0.2 , now u can update macOS Sequoia with the EFI， WiFi need oclp patch
> 
> i used the latest config.plist and file , when i boot into system which is sequoia ,the oclp patch is gray in app, how can it be applied?

https://youtu.be/73_9zTFR34Y?si=eWoPS-omC0eL0gYX

**Comment by WuLongMiTaoLaiYiDa** [comment]
> https://youtu.be/73_9zTFR34Y?si=eWoPS-omC0eL0gYX

https://github.com/hackintosh-club/intel-nuc10/releases/tag/oclp

rest nvram and try this

**Comment by guliujian** [comment]
thanks for help, it works after apply the patch

**Comment by jktan0504** [comment]
Hi sorry to disturb.
@WuLongMiTaoLaiYiDa @apollohackintosh @guliujian 

I tried https://youtu.be/73_9zTFR34Y?si=eWoPS-omC0eL0gYX

1.选择 Post-Install Root Patch 按钮
2.选择 Start Root Patching 按钮
备注：如此按钮呈灰色，请重启计算机并在OC界面按空格键后选择reset nvram选项，进入系统后再次执行
3. 选择 Reboot 按钮 重启计算机

Select the Post Install Root Patch button
Select the Start Root Patching button
Note: When this button appears gray , Please restart the computer and press the Spacebar on the OC UI to select the reset nvram option. After entering the system, execute it again
Select the Reboot button to restart the computer

![Screenshot 2024-11-21 at 5 09 07 PM](https://github.com/user-attachments/assets/64533d2a-0b83-4109-a752-b09bdc8fe065)
the `Start Root Patching button` still appear gray. Please help

and yes my wifi now is not working.

![Screenshot 2024-11-21 at 5 07 14 PM](https://github.com/user-attachments/assets/f2470f1d-9480-4f0c-bb28-c93738d60559)

thanks for sharing your knowledge.
