### ISSUE TITLE
add 0055 bios file

### ISSUE THREAD

**Issue by aryanrajseo** [hackintosh-club/intel-nuc10#137]
we are not able to find the bios 0055 for nuc10. latest bios shows variable writing error like https://github.com/hackintosh-club/intel-nuc10/issues/104

I found 0052 https://drivers.softpedia.com/dyn-search.php?search_term=NUC10I5FNH&p_sortby=0&p_category=10&p_picks=&p_license=&p_lastupdate=0&p_whatos=0

https://www.asus.com/supportonly/nuc10i5fnh/helpdesk_bios/

**Comment by mrasong** [comment]
you kidding me?the bios files already in the source code BIOS folder.On Oct 19, 2024, at 17:12, Aryan Raj ***@***.***> wrote:﻿
we are not able to find the bios 0055 for nuc10. latest bios shows variable writing error like #104
I found 0052 https://drivers.softpedia.com/dyn-search.php?search_term=NUC10I5FNH&p_sortby=0&p_category=10&p_picks=&p_license=&p_lastupdate=0&p_whatos=0
https://www.asus.com/supportonly/nuc10i5fnh/helpdesk_bios/

**Comment by mrasong** [comment]
intel-nuc10/BIOS at master · hackintosh-club/intel-nuc10github.comMessage ID: ***@***.***>

**Comment by aryanrajseo** [comment]
my apologies, it was all invisible for me as i was only checking the description and latest release. i get it now. thank you.
