### ISSUE TITLE
14.7.1 not installing

### ISSUE THREAD

**Issue by mcinp** [hackintosh-club/intel-nuc10#139]
Hi, I tried installing macOS on NUC10i7FN using your, but without success (it restarts during initial boot from install medium).
I used current release with 147.7.1 and previous release with 14.0.
I'm probably missing something so here's what I did:

- set CFGLock to 0
- updated BIOS to 0061
- made neccessary adjustments to BIOS settings
- prepared media with EFI from the repo
- changed config.plist to include only proper AirportItlwm kext

I also tried changing SN, MLB, UUID to newly generated values.

Are there any steps that I'm missing?

**Comment by WuLongMiTaoLaiYiDa** [comment]
1. download the Latest EFI [v1.0.2.1115 OpenCore 1.0.2 fixed](https://github.com/hackintosh-club/intel-nuc10/releases/download/v1.0.2.1115/NUC10-EFI-v1.0.2.1115.tar.gz)
2. change SN, MLB, UUID
3. OC UI Press Space chose Reset Nvram 
no need to change AirportItlwm.kext

**Comment by egops** [comment]
> 1. download the Latest EFI [v1.0.2.1115 OpenCore 1.0.2 fixed](https://github.com/hackintosh-club/intel-nuc10/releases/download/v1.0.2.1115/NUC10-EFI-v1.0.2.1115.tar.gz)
> 2. change SN, MLB, UUID (OCAT version must correspond to the OC version ：1.0.2）
> 3. OC UI Press Space select Reset Nvram
>    no need to change AirportItlwm.kext

大佬, 我升级到15.1.1之后, wifi不能用了, 有没有办法解决?

**Comment by WuLongMiTaoLaiYiDa** [comment]
> > 1. download the Latest EFI [v1.0.2.1115 OpenCore 1.0.2 fixed](https://github.com/hackintosh-club/intel-nuc10/releases/download/v1.0.2.1115/NUC10-EFI-v1.0.2.1115.tar.gz)
> > 2. change SN, MLB, UUID (OCAT version must correspond to the OC version ：1.0.2）
> > 3. OC UI Press Space select Reset Nvram
> >    no need to change AirportItlwm.kext
> 
> 大佬, 我升级到15.1.1之后, wifi不能用了, 有没有办法解决?

[issues-140](https://github.com/hackintosh-club/intel-nuc10/issues/140)

**Comment by mcinp** [comment]
Thanks. Using the new EFI folder I was able to install 14.7.2.
