### ISSUE TITLE
MacOS Sequoia 15.1.1 - Wifi & Bluetooth are not working

### ISSUE THREAD

**Issue by jktan0504** [hackintosh-club/intel-nuc10#140]
Hi sorry to disturb.

I tried https://youtu.be/73_9zTFR34Y?si=eWoPS-omC0eL0gYX
OpenCore Legacy Patcher 2.1.2

1.选择 Post-Install Root Patch 按钮
2.选择 Start Root Patching 按钮
备注：如此按钮呈灰色，请重启计算机并在OC界面按空格键后选择reset nvram选项，进入系统后再次执行
3. 选择 Reboot 按钮 重启计算机

Select the Post Install Root Patch button
Select the Start Root Patching button
Note: When this button appears gray , Please restart the computer and press the Spacebar on the OC UI to select the reset nvram option. After entering the system, execute it again
Select the Reboot button to restart the computer

![Screenshot 2024-11-21 at 5 09 07 PM](https://github.com/user-attachments/assets/dc5be43a-510d-4aaf-bc92-ccb758874a15)

the Start Root Patching button still appear gray. Please help

Then, I tried again OpenCore Legacy Patcher 1.6.0 from https://github.com/hackintosh-club/intel-nuc10/releases/tag/oclp
![Screenshot 2024-11-21 at 5 47 17 PM](https://github.com/user-attachments/assets/1eac2906-1aa3-47a5-81c4-50b28bac9c7b)

I cant run OpenCore Legacy Patcher 1.6.0 

and now, yes my wifi is still not working. 
![Screenshot 2024-11-21 at 5 07 14 PM](https://github.com/user-attachments/assets/2ee97b13-882c-43e8-ba68-139b984fdc57)

![Screenshot 2024-11-21 at 6 48 52 PM](https://github.com/user-attachments/assets/52eb2c77-417a-468a-876c-dd3ab384ad9d)

I am using `https://github.com/hackintosh-club/intel-nuc10/releases/tag/v1.0.2.1115` 

thanks for sharing your knowledge. Please help.
感谢大大

**Comment by jktan0504** [comment]
![Screenshot 2024-11-21 at 6 54 26 PM](https://github.com/user-attachments/assets/5271711e-9226-49de-be8c-b2521825b310)

**Comment by WuLongMiTaoLaiYiDa** [comment]
https://github.com/laobamac/OCLP-Mod/releases/download/2.4.1/OpenCore-Patcher.pkg      

download this  mod verison and patch

**Comment by jktan0504** [comment]
Thanks. By using this mod version, my wifi and bluetooth are working now.

Thank you so much @WuLongMiTaoLaiYiDa 

感谢大大🙏
