### ISSUE TITLE
[Enhancement] 修复雷电3接外接显卡EGPU无法驱动的问题

### ISSUE THREAD

**Issue by Snowail** [hackintosh-club/intel-nuc10#88]
我使用这个EFI发现EGPU接上去以后能识别到显卡但是无法驱动，显卡拓展坞的USB接口也无法使用
系统报告PCI设备里面能识别JHL7540 NHI但是显卡拓展坞是在DSL6540下面，这两个控制器都应该是能被macOS支持的

参考[SSDT for Thunderbolt 3 Hotplug](https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/)，将SSDT-NUC10.aml中_SB_.PCI0.RP05部分独立出来，添加SSDT-TB3.aml，稍微修改了下设备名称

现在显卡可以被正常识别并驱动了，USB接口也能正常使用

![截屏2022-12-02 09 57 18](https://user-images.githubusercontent.com/45956036/205198744-78607905-0c5b-4c40-b8a5-3e660ead871d.png)
![截屏2022-12-02 09 58 41](https://user-images.githubusercontent.com/45956036/205198750-c56a9699-e7ed-4a00-8b28-c6f4d11dd748.png)

附上修改过的SSDT-NUC10.aml和SSDT-TB3.aml
[ACPI.zip](https://github.com/hackintosh-efi/intel-nuc10/files/10137585/ACPI.zip)

⚠️注意！请不要禁用核显
EGPU并不能直接在启动过程中禁用核显点亮显示器，只能在进入macOS后拓展显示器
对于只有一台显示器想接独显，可以这样操作切换到独显：

在接nuc的HDMI接口启动macOS后，点左上苹果图标>锁定屏幕>按Ecs熄灭显示器，等显示器熄灭后拔掉nuc上的HDMI，插到外接显卡上，然后按任意键或者nuc电源键重新点亮屏幕，此时显示器应该成功切换到独显

**Comment by WuLongMiTaoLaiYiDa** [comment]
2024年3月重新制作了EFI文件，无需加入SSDT，在开机前接入egpu，进系统后即可检测到外接显卡，已测试睡眠唤醒后egpu没有任何问题。
无论如何，感谢你的测试和反馈！
