### ISSUE TITLE
v0.8.8.0102 OpenCore 0.8.8 wifi doesn't work

### ISSUE THREAD

**Issue by duyquang91** [hackintosh-club/intel-nuc10#92]
I tried to update open core to this version `v0.8.8.0102` on my current Monterey, the wifi kext caused the MacOS unable to boot, disabled wifi on Bios or disable on open core then can boot but no wifi at all. Tried with my current wifi kext also didn't work.

I also tried to create a new `Ventura` installer on USB with this `v0.8.8.0102`, wifi show scanning but no networks found.

**Comment by mrasong** [comment]
try to use the latest wifi drive.

**Comment by steve-gxs** [comment]
@mrasong Where to get the latest wifi driver?

**Comment by mrasong** [comment]
The README page show all kexts links.

**Comment by duyquang91** [comment]
@mrasong I tried to download the latest version of wifi kext, still doesn't work

**Comment by WuLongMiTaoLaiYiDa** [comment]
Now,Intel wifi work well 
have fun with hacintosh ;-)
