### ISSUE TITLE
too much power error on front USB 3 port

### ISSUE THREAD

**Issue by claud9999** [hackintosh-club/intel-nuc10#95]
When I connect my iPhone to the front USB port, I get an error notification "USB Accessory Disabled - Unplug the accessory using too much power to re-enable USB devices." Plugging the same phone on the back USB port doesn't seem to generate this error. Is this something to fix in the Kexts or does the front USB port not provide higher power output?

**Comment by mrasong** [comment]
USB-A or USB-C？

**Comment by WuLongMiTaoLaiYiDa** [comment]
update EFI  2024  it's all done
