### ISSUE TITLE
大佬 安装时卡在这个安装macos ventura应用程序副本已损坏不能用来安装macos

### ISSUE THREAD

**Issue by Jack-bin183** [hackintosh-club/intel-nuc10#97]
安装时，选择安装Mac OS。弹窗 这个安装macos ventura应用程序副本已损坏不能用来安装macos。

镜像 13.2
i7 10710 Intel WiFi 蓝牙原版
guthub 最新efi

试过断网修改日期。无效

求解，不胜感激

**Comment by Jack-bin183** [comment]
U盘的问题。安装好了

**Comment by mrasong** [comment]
一般这种情况 可能就是盘的问题了

**Comment by Jack-bin183** [comment]
谢谢大佬 还有一个问题就是nuc10的bios能降级吗。我现在是最新的BIOS。cfg解锁不了

**Comment by mrasong** [comment]
可以降级 README 里有讲，源码里也有0055的BIOS文件
