### ISSUE TITLE
How can we directly update MacOs to latest version ?

### ISSUE THREAD

**Issue by jktan0504** [hackintosh-club/intel-nuc10#98]
Hi 大佬，I met this problem every time I try to directly update the MacOS.

Instead of fresh install everything again, is that any solution for me to directly update it ?

![Screenshot 2023-03-30 at 11 55 09 AM](https://user-images.githubusercontent.com/29939040/228725411-a21f8bb4-dc60-48c2-8f86-48379c1e8c81.png)

Thanks

**Comment by apollohackintosh** [comment]
Having the same issue as above. SMBIOS is also valid. Been upgrading since Big Sur with no issues.
