### ISSUE TITLE
[v0.9.1.0403 OpenCore 0.9.1] Bluetooth issue

### ISSUE THREAD

**Issue by SalvatoreAD** [hackintosh-club/intel-nuc10#99]
Hi, I installed v0.9.1.0403 OpenCore 0.9.1 and bluetooth doesn't work anymore. 
if i try to activate it it won't activate. 
Tried restarting the nuc, bluetooth turns on, finds devices, but won't connect.

Can you help me?

**Comment by duyquang91** [comment]
Update wifi kext to last stable version will fix the bluetooth issue
